/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PharmecyProject;



import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author MD. AL MAMUN
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    private ImageIcon img, img2;

    public LogIn() {
        img = new ImageIcon("src/image/login.png");
        this.setIconImage(img.getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        log = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sinup = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LogIn Page");
        setBackground(new java.awt.Color(0, 204, 255));
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText(" User Id / Email:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText(" Password:");

        user.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password.setEchoChar('*');

        log.setBackground(new java.awt.Color(0, 0, 0));
        log.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("LogIn");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("If you are a new member plz ");

        sinup.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sinup.setForeground(new java.awt.Color(0, 255, 0));
        sinup.setText("SignUp");
        sinup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinupMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("first !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinup, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(password))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(log)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinupMouseClicked
        // TODO add your handling code here:
        Signing sin = new Signing();
        sin.setVisible(true);
        sin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_sinupMouseClicked


    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        String s = user.getText().toLowerCase();
        String p = password.getText();
        if (s.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide your valid Email or User Id !", "Requard!", 2);
        } else if (p.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide your valid Password !", "Requard!", 2);
        } else {
            try {
//                Class.forName("oracle.jdbc.driver.OracleDriver");
//                Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "user_a", "2301");
                //call the connection class
                Connection connect = ConnectionClass.getconnect();

                Statement st = connect.createStatement();

//            ResultSet check = st.executeQuery("select EMAIL from CHECKSEQ");
//
//
//            boolean b = false;
//            while (check.next()) {
//                String mil = check.getString("Email");
//               
//                for(int i=1;i<=check.getRow();i++){
//                    if(mil.equals(s)){
//                    b=true;
//                    break;
//                    }
//                 
//                }
//                
//            }
//           if(b==false){
//           JOptionPane.showMessageDialog(null, "You cannot a member of this Program! \n Please Sign Up first. Then LogIn.","Inavalid",2);
//           }
                ResultSet em = st.executeQuery("select EMAIL,PASSWORD from register where EMAIL=" + "'" + s + "'");

                if (em.next()) {
                    String dm = em.getString(1);
                    String dp = em.getString(2);

                    if (s.equals(dm) && p.equals(dp)) {

                        WelcomePage welcp = new WelcomePage();
                        welcp.setVisible(true);
                        JOptionPane.showMessageDialog(null, "WELCOME ! " + dm + "", "", -1);

//                        //WELCOME PAGE
//                        Dimension windowSize = Toolkit.getDefaultToolkit().getScreenSize();
//                        int w = windowSize.width / 2;
//                        int h = windowSize.height / 2;
//
//                        JFrame jf = new JFrame();
//                        img2 = new ImageIcon("src/image/Welcome.png");
//                        jf.setIconImage(img2.getImage());
//                        jf.setSize(w, h);
//                        jf.setLocationRelativeTo(null);
//                        Container c = jf.getContentPane();
//                        c.setLayout(null);
//                        c.setBackground(Color.black);
//                        jf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//                        jf.setVisible(true);
//                        
//                        //CRETA LABEL
//                        JLabel lb1, lb2, lb3, lb4;
//                        Font font = new Font("Times new roman", Font.BOLD, 20);
//                        lb1 = new JLabel("Hello! " + dm);
//                        lb1.setBounds(10, 20, 350, 30);
//                        lb1.setFont(font);
//                        lb1.setForeground(Color.WHITE);
//                        c.add(lb1);
//                        lb2 = new JLabel("You are most welcome to our Pharmacy Management System!");
//                        lb2.setBounds(10, 60, 550, 30);
//                        lb2.setFont(font);
//                        lb2.setForeground(Color.WHITE);
//                        c.add(lb2);
//                        lb3 = new JLabel("Thanks by");
//                        lb3.setBounds(10, 120, 350, 30);
//                        lb3.setFont(font);
//                        lb3.setForeground(Color.WHITE);
//                        c.add(lb3);
//                        lb4 = new JLabel("Md. Mamun.");
//                        lb4.setBounds(10, 150, 350, 30);
//                        lb4.setFont(font);
//                        lb4.setForeground(Color.WHITE);
//                        c.add(lb4);
                        dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "your password can't match with this user ");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please SignUp first! you are a not a member.", "Invalid", 2);
                    Signing sin1 = new Signing();
                    sin1.setVisible(true);
                }

            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e);
                
            }

        }
    }//GEN-LAST:event_logActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton log;
    public javax.swing.JPasswordField password;
    public javax.swing.JLabel sinup;
    public javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
